/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.*;
/**
 *
 * @author agash
 */
public class Employer_landing_page extends javax.swing.JPanel {

    /**
     * Creates new form Emplyer_landing_page
     */
    private Student_details_list students;
    private Professor_details_list professors;
    private Course_details_list  courses;
    private JPanel bottom_panel;
    private Student_details student;
    private Professor_details professor;
    
    public Employer_landing_page(JPanel bottom_panel, Student_details_list students, Professor_details_list professors, Course_details_list courses) {
        initComponents();
        this.bottom_panel = bottom_panel;
        this.students = students;
        this.professors = professors;
        this.courses = courses;        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_students = new javax.swing.JButton();
        btn_professors = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(null);

        btn_students.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btn_students.setText("View Students");
        btn_students.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_studentsActionPerformed(evt);
            }
        });
        add(btn_students);
        btn_students.setBounds(670, 220, 173, 40);

        btn_professors.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btn_professors.setText("View Professors");
        btn_professors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_professorsActionPerformed(evt);
            }
        });
        add(btn_professors);
        btn_professors.setBounds(670, 350, 173, 40);

        btn_back.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        btn_back.setText("< Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        add(btn_back);
        btn_back.setBounds(720, 500, 81, 35);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("  Employeer       ");
        add(jLabel1);
        jLabel1.setBounds(27, 6, 1512, 44);

        jLabel2.setIcon(new javax.swing.ImageIcon("/Users/agash/Documents/The Boys/Employee.png")); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(0, 0, 1600, 920);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_studentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_studentsActionPerformed
        // TODO add your handling code here:
        Employer_students employer_students = new Employer_students(bottom_panel, students);
        bottom_panel.add("employer_students",employer_students);
        CardLayout layout = (CardLayout) bottom_panel.getLayout();
        layout.next(bottom_panel);

    }//GEN-LAST:event_btn_studentsActionPerformed

    private void btn_professorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_professorsActionPerformed
        // TODO add your handling code here:
        Employer_professors employer_professors = new Employer_professors(bottom_panel, professors);
        bottom_panel.add("employer_professors",employer_professors);
        CardLayout layout = (CardLayout) bottom_panel.getLayout();
        layout.next(bottom_panel);
    }//GEN-LAST:event_btn_professorsActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        bottom_panel.remove(this);
        CardLayout layout = (CardLayout) bottom_panel.getLayout();
        layout.previous(bottom_panel);
    }//GEN-LAST:event_btn_backActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_professors;
    private javax.swing.JButton btn_students;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
