/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JPanel;
import model.*;
import java.awt.CardLayout;

/**
 *
 * @author agash
 */
public class LandingPage extends javax.swing.JPanel {

    /**
     * Creates new form LandingPage
     */
    
    private Student_details_list students;
    private Professor_details_list professors;
    private Course_details_list  courses;
    private JPanel bottom_panel;
    
    public LandingPage(JPanel bottom_panel, Student_details_list students, Professor_details_list professors, Course_details_list courses) {
        initComponents();
        this.bottom_panel = bottom_panel;
        this.students = students;
        this.professors = professors;
        this.courses = courses;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_student = new javax.swing.JButton();
        btn_prof = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        btn_admin = new javax.swing.JButton();
        btn_emp = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(null);

        btn_student.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        btn_student.setText("Student");
        btn_student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_studentActionPerformed(evt);
            }
        });
        add(btn_student);
        btn_student.setBounds(664, 129, 148, 42);

        btn_prof.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        btn_prof.setText("Professor");
        btn_prof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_profActionPerformed(evt);
            }
        });
        add(btn_prof);
        btn_prof.setBounds(664, 236, 148, 42);

        btn_back.setFont(new java.awt.Font("Helvetica Neue", 0, 17)); // NOI18N
        btn_back.setText("< Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        add(btn_back);
        btn_back.setBounds(699, 623, 84, 33);

        btn_admin.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        btn_admin.setText("Admin");
        btn_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adminActionPerformed(evt);
            }
        });
        add(btn_admin);
        btn_admin.setBounds(664, 460, 148, 42);

        btn_emp.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        btn_emp.setText("Employee");
        btn_emp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_empActionPerformed(evt);
            }
        });
        add(btn_emp);
        btn_emp.setBounds(664, 343, 148, 42);

        jLabel2.setIcon(new javax.swing.ImageIcon("/Users/agash/Documents/The Boys/Student.png")); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(2, -3, 1500, 1000);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_studentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_studentActionPerformed
        // TODO add your handling code here:
        Stu_landing student_landing = new Stu_landing(bottom_panel, students, professors, courses);
        bottom_panel.add("student_landing",student_landing);
        CardLayout layout = (CardLayout) bottom_panel.getLayout();
        layout.next(bottom_panel);

    }//GEN-LAST:event_btn_studentActionPerformed

    private void btn_profActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_profActionPerformed
        // TODO add your handling code here:
        Prof_Landingpage prof_landing = new Prof_Landingpage(bottom_panel, students, professors, courses);
        bottom_panel.add("prof_landing",prof_landing);
        CardLayout layout = (CardLayout) bottom_panel.getLayout();
        layout.next(bottom_panel);
        
    }//GEN-LAST:event_btn_profActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        bottom_panel.remove(this);
        CardLayout layout = (CardLayout) bottom_panel.getLayout();
        layout.previous(bottom_panel);
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adminActionPerformed
        // TODO add your handling code here:
        Admin_Stats admin_stats = new Admin_Stats(bottom_panel, students, professors, courses);
        bottom_panel.add("admin_stats",admin_stats);
        CardLayout layout = (CardLayout) bottom_panel.getLayout();
        layout.next(bottom_panel);        
    }//GEN-LAST:event_btn_adminActionPerformed

    private void btn_empActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_empActionPerformed
        // TODO add your handling code here:
        Employer_landing_page employer_landing_page = new Employer_landing_page(bottom_panel, students, professors, courses);
        bottom_panel.add("employer_landing_page",employer_landing_page);
        CardLayout layout = (CardLayout) bottom_panel.getLayout();
        layout.next(bottom_panel);       
    }//GEN-LAST:event_btn_empActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_admin;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_emp;
    private javax.swing.JButton btn_prof;
    private javax.swing.JButton btn_student;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
