/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.*;

/**
 *
 * @author agash
 */
public class Prof_register extends javax.swing.JPanel {

    /**
     * Creates new form Prof_register
     */
    private Student_details_list students;
    private Professor_details_list professors;
    private Course_details_list  courses;
    private JPanel bottom_panel;  
    
    public Prof_register(JPanel bottom_panel, Student_details_list students, Professor_details_list professors, Course_details_list courses) {
        initComponents();
        this.bottom_panel = bottom_panel;
        this.students = students;
        this.professors = professors;
        this.courses = courses;         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbl_name = new javax.swing.JLabel();
        lbl_mailid = new javax.swing.JLabel();
        txtfield_mailid = new javax.swing.JTextField();
        txtfield_name = new javax.swing.JTextField();
        btn_register = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        lbl_region = new javax.swing.JLabel();
        lbl_speciality = new javax.swing.JLabel();
        txtfield_speciality = new javax.swing.JTextField();
        txtfield_region = new javax.swing.JTextField();
        lbl_userid = new javax.swing.JLabel();
        lbl_password = new javax.swing.JLabel();
        txtfield_userid = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Professor register page");
        add(jLabel1);
        jLabel1.setBounds(6, 26, 1488, 40);

        lbl_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_name.setText("Name");
        add(lbl_name);
        lbl_name.setBounds(621, 161, 69, 34);

        lbl_mailid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_mailid.setText("Mail ID");
        add(lbl_mailid);
        lbl_mailid.setBounds(621, 246, 69, 34);
        add(txtfield_mailid);
        txtfield_mailid.setBounds(739, 247, 245, 34);

        txtfield_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfield_nameActionPerformed(evt);
            }
        });
        add(txtfield_name);
        txtfield_name.setBounds(739, 162, 245, 34);

        btn_register.setText("Register");
        btn_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registerActionPerformed(evt);
            }
        });
        add(btn_register);
        btn_register.setBounds(739, 652, 78, 36);

        btn_back.setText("< Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        add(btn_back);
        btn_back.setBounds(739, 723, 78, 36);

        lbl_region.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_region.setText("Region");
        add(lbl_region);
        lbl_region.setBounds(621, 331, 69, 34);

        lbl_speciality.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_speciality.setText("Speciality");
        add(lbl_speciality);
        lbl_speciality.setBounds(621, 416, 69, 34);
        add(txtfield_speciality);
        txtfield_speciality.setBounds(739, 417, 245, 34);

        txtfield_region.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfield_regionActionPerformed(evt);
            }
        });
        add(txtfield_region);
        txtfield_region.setBounds(739, 332, 245, 34);

        lbl_userid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_userid.setText("User ID");
        add(lbl_userid);
        lbl_userid.setBounds(621, 501, 69, 34);

        lbl_password.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_password.setText("Password");
        add(lbl_password);
        lbl_password.setBounds(621, 586, 69, 34);

        txtfield_userid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfield_useridActionPerformed(evt);
            }
        });
        add(txtfield_userid);
        txtfield_userid.setBounds(739, 502, 245, 34);
        add(jPasswordField1);
        jPasswordField1.setBounds(739, 587, 245, 34);

        jLabel2.setIcon(new javax.swing.ImageIcon("/Users/agash/Documents/The Boys/Student.png")); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(2, -3, 1500, 1000);
    }// </editor-fold>//GEN-END:initComponents

    private void txtfield_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfield_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfield_nameActionPerformed

    private void btn_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registerActionPerformed
        // TODO add your handling code here:
        for (Professor_details professor: professors.getProfessor_list()){
            if(professor.getUserid()==Integer.parseInt(txtfield_userid.getText())){
                JOptionPane.showMessageDialog(null, "This User ID is already taken, Kindly choose a different User ID");
                txtfield_userid.setText("");
            } 
        }
        
        try {
            if (!txtfield_name.getText().trim().isEmpty() && !txtfield_mailid.getText().trim().isEmpty() && !txtfield_region.getText().trim().isEmpty() && !txtfield_speciality.getText().trim().isEmpty() && !txtfield_userid.getText().trim().isEmpty() && !String.valueOf(jPasswordField1.getPassword()).isEmpty()){
                Professor_details professor = professors.add_professor();
                professor.setName(txtfield_name.getText());
                professor.setMailid(txtfield_mailid.getText());
                professor.setRegion(txtfield_region.getText());
                professor.setSpeciality(txtfield_speciality.getText());
                professor.setUserid(Integer.parseInt(txtfield_userid.getText()));
                professor.setPassword(String.valueOf(jPasswordField1.getPassword()));
                JOptionPane.showMessageDialog(null, "User registered successfully!");

                txtfield_name.setText("");
                txtfield_mailid.setText("");
                txtfield_region.setText("");
                txtfield_speciality.setText("");
                txtfield_userid.setText("");
                jPasswordField1.setText("");
            }
            else {
                JOptionPane.showMessageDialog(null, "Kindly fill all the fields");
            }
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Kindly fill with appropriate details"); 
            txtfield_name.setText("");
            txtfield_mailid.setText("");
            txtfield_region.setText("");
            txtfield_speciality.setText("");
            txtfield_userid.setText("");
            jPasswordField1.setText("");
        }

    }//GEN-LAST:event_btn_registerActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        bottom_panel.remove(this);
        CardLayout layout = (CardLayout) bottom_panel.getLayout();
        layout.previous(bottom_panel);         
    }//GEN-LAST:event_btn_backActionPerformed

    private void txtfield_regionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfield_regionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfield_regionActionPerformed

    private void txtfield_useridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfield_useridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfield_useridActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_register;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel lbl_mailid;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_region;
    private javax.swing.JLabel lbl_speciality;
    private javax.swing.JLabel lbl_userid;
    private javax.swing.JTextField txtfield_mailid;
    private javax.swing.JTextField txtfield_name;
    private javax.swing.JTextField txtfield_region;
    private javax.swing.JTextField txtfield_speciality;
    private javax.swing.JTextField txtfield_userid;
    // End of variables declaration//GEN-END:variables
}
