/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import model.*;
import java.time.LocalDate;

/**
 *
 * @author agash
 */
public class Stu_emp_msg extends javax.swing.JPanel {

    /**
     * Creates new form Stu_emp_msg
     */
    private JPanel bottom_panel;
    private Student_details student_details;
    private String chat;
    
    
    public Stu_emp_msg(JPanel bottom_panel, Student_details student_details) {
        initComponents();
        this.chat = student_details.getChats();
        this.bottom_panel = bottom_panel;
        this.student_details = student_details;
        if (chat != null && !chat.trim().isEmpty()) {
            jTextArea1.setText(chat);
        }
        else{
            this.chat ="";
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        txt_chat = new javax.swing.JTextField();
        btn_sendchat = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setLayout(null);

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Student Portal");
        add(jLabel8);
        jLabel8.setBounds(6, 6, 1494, 23);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1);
        jScrollPane1.setBounds(483, 169, 530, 209);
        add(txt_chat);
        txt_chat.setBounds(586, 419, 452, 23);

        btn_sendchat.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btn_sendchat.setText("Send");
        btn_sendchat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sendchatActionPerformed(evt);
            }
        });
        add(btn_sendchat);
        btn_sendchat.setBounds(1062, 414, 91, 29);

        btn_back.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btn_back.setText("<Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        add(btn_back);
        btn_back.setBounds(716, 548, 82, 32);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel1.setText("Enter your message");
        add(jLabel1);
        jLabel1.setBounds(407, 416, 173, 25);

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Message Employee");
        add(jLabel2);
        jLabel2.setBounds(640, 140, 213, 23);

        jLabel3.setIcon(new javax.swing.ImageIcon("/Users/agash/Documents/The Boys/Student.png")); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(2, -3, 1500, 1000);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_sendchatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sendchatActionPerformed
        // TODO add your handling code here:
        LocalDate myObj = LocalDate.now();

        this.chat = this.chat+String.valueOf(myObj)+" - "+student_details.getName()+": "+txt_chat.getText()+"\r\n" ;
        jTextArea1.setText(this.chat);
        this.student_details.setChats(this.chat);
    }//GEN-LAST:event_btn_sendchatActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        bottom_panel.remove(this);
        CardLayout layout = (CardLayout) bottom_panel.getLayout();
        layout.previous(bottom_panel);
    }//GEN-LAST:event_btn_backActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_sendchat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField txt_chat;
    // End of variables declaration//GEN-END:variables
}
