/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import javax.swing.JPanel;
import model.*;
import javax.swing.JOptionPane;

/**
 *
 * @author manish
 */
public class Stu_newuser extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    private Student_details_list students;
    private Professor_details_list professors;
    private Course_details_list  courses;
    private JPanel bottom_panel;
    
    public Stu_newuser(JPanel bottom_panel, Student_details_list students, Professor_details_list professors, Course_details_list courses) {
        initComponents();
        this.bottom_panel = bottom_panel;
        this.students = students;
        this.professors = professors;
        this.courses = courses;        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtstuname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtstumail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtsturegion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtstuaspiring = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();
        txtstuuserid = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btn_save = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Student Portal");

        setLayout(null);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Name");
        add(jLabel1);
        jLabel1.setBounds(521, 145, 116, 36);
        add(txtstuname);
        txtstuname.setBounds(668, 146, 312, 36);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Mail ID");
        add(jLabel2);
        jLabel2.setBounds(513, 232, 124, 36);
        add(txtstumail);
        txtstumail.setBounds(668, 233, 312, 36);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Region");
        add(jLabel3);
        jLabel3.setBounds(513, 319, 124, 36);
        add(txtsturegion);
        txtsturegion.setBounds(668, 320, 312, 36);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Aspiring to be");
        add(jLabel4);
        jLabel4.setBounds(513, 405, 124, 36);

        txtstuaspiring.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstuaspiringActionPerformed(evt);
            }
        });
        add(txtstuaspiring);
        txtstuaspiring.setBounds(668, 406, 312, 36);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Password");
        add(jLabel5);
        jLabel5.setBounds(513, 572, 124, 36);

        btn_back.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btn_back.setText("<Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        add(btn_back);
        btn_back.setBounds(687, 732, 96, 36);

        txtstuuserid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstuuseridActionPerformed(evt);
            }
        });
        add(txtstuuserid);
        txtstuuserid.setBounds(668, 492, 312, 36);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("User ID");
        add(jLabel6);
        jLabel6.setBounds(527, 491, 110, 36);

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Student Portal");
        add(jLabel8);
        jLabel8.setBounds(6, 6, 1494, 23);

        btn_save.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btn_save.setText("Save");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });
        add(btn_save);
        btn_save.setBounds(687, 646, 96, 36);
        add(jPasswordField1);
        jPasswordField1.setBounds(668, 578, 312, 36);

        jLabel9.setIcon(new javax.swing.ImageIcon("/Users/agash/Documents/The Boys/Student.png")); // NOI18N
        add(jLabel9);
        jLabel9.setBounds(2, -3, 1500, 1000);
    }// </editor-fold>//GEN-END:initComponents

    private void txtstuaspiringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstuaspiringActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstuaspiringActionPerformed

    private void txtstuuseridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstuuseridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstuuseridActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        bottom_panel.remove(this);
        CardLayout layout = (CardLayout) bottom_panel.getLayout();
        layout.previous(bottom_panel);      
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        // TODO add your handling code here:
        
        for (Student_details student: students.getStudents_list()){
            if(student.getUser_id()==Integer.parseInt(txtstuuserid.getText())){
                JOptionPane.showMessageDialog(null, "This User ID is already taken, Kindly choose a different User ID");
                txtstuuserid.setText("");
            }
        }
        
        try{
            if (!txtstuname.getText().trim().isEmpty() && !txtstumail.getText().trim().isEmpty() && !txtsturegion.getText().trim().isEmpty() && !txtstuaspiring.getText().trim().isEmpty() && !String.valueOf(jPasswordField1.getPassword()).trim().isEmpty() && !txtstuuserid.getText().trim().isEmpty())
            {
                Student_details student = students.add_student();
                student.setName(txtstuname.getText());
                student.setMailid(txtstumail.getText());
                student.setRegion(txtsturegion.getText());
                student.setAspire(txtstuaspiring.getText());
                student.setPassword(String.valueOf(jPasswordField1.getPassword()));
                student.setUser_id(Integer.parseInt(txtstuuserid.getText()));
                JOptionPane.showMessageDialog(null, "User registered successfully!");

                txtstuname.setText("");
                txtstumail.setText("");
                txtsturegion.setText("");
                txtstuaspiring.setText("");
                jPasswordField1.setText("");
                txtstuuserid.setText("");
                
                bottom_panel.remove(this);
                CardLayout layout = (CardLayout) bottom_panel.getLayout();
                layout.previous(bottom_panel);  
            }
            else{
                JOptionPane.showMessageDialog(null, "Kindly fill all the details");
            }
            
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, "Kindly fill with appropriate details");
            txtstuname.setText("");
            txtstumail.setText("");
            txtsturegion.setText("");
            txtstuaspiring.setText("");
            jPasswordField1.setText("");
            txtstuuserid.setText("");
        }
        
               
    }//GEN-LAST:event_btn_saveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_save;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField txtstuaspiring;
    private javax.swing.JTextField txtstumail;
    private javax.swing.JTextField txtstuname;
    private javax.swing.JTextField txtsturegion;
    private javax.swing.JTextField txtstuuserid;
    // End of variables declaration//GEN-END:variables
}
