/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.*;


/**
 *
 * @author manish
 */
public class Stu_courselandingpanel extends javax.swing.JPanel {

    /**
     * Creates new form courselandingpanel
     */
    private Student_details_list students;
    private Professor_details_list professors;
    private Course_details_list  courses;
    private JPanel bottom_panel;
    private Student_details student_details;
    private ArrayList<ArrayList<Object>> courses_registered = new ArrayList<>(); 
    private ArrayList<Object> coursePair;
    private ArrayList<ArrayList<String>> grades = new ArrayList();
    private Course_details Course;
    private boolean found;
    private ArrayList<ArrayList<String>> question_bank = new ArrayList<>();
    
    public Stu_courselandingpanel(JPanel bottom_panel, Student_details_list students, Professor_details_list professors, Course_details_list courses,Student_details student_details,ArrayList<Object> coursePair) {
        initComponents();
        this.bottom_panel = bottom_panel;
        this.students = students;
        this.professors = professors;
        this.courses = courses;
        this.student_details = student_details;
        this.courses_registered = student_details.getCourses_registered();
        this.coursePair = coursePair;
        this.grades = student_details.getGrades();
        Course_details Course = (Course_details) coursePair.get(0);
        this.Course = Course;
        this.question_bank = Course.getExams();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        btn_syllabus = new javax.swing.JButton();
        btn_announce = new javax.swing.JButton();
        btn_chat = new javax.swing.JButton();
        btn_exam = new javax.swing.JButton();
        btn_rating = new javax.swing.JButton();
        btn_feedback = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(null);

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Student Portal");
        add(jLabel8);
        jLabel8.setBounds(6, 6, 1494, 45);

        btn_syllabus.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btn_syllabus.setText("Syllabus");
        btn_syllabus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_syllabusActionPerformed(evt);
            }
        });
        add(btn_syllabus);
        btn_syllabus.setBounds(703, 132, 162, 40);

        btn_announce.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btn_announce.setText("Announcements");
        btn_announce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_announceActionPerformed(evt);
            }
        });
        add(btn_announce);
        btn_announce.setBounds(703, 222, 162, 40);

        btn_chat.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btn_chat.setText("Chat with peer");
        btn_chat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chatActionPerformed(evt);
            }
        });
        add(btn_chat);
        btn_chat.setBounds(703, 312, 162, 40);

        btn_exam.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btn_exam.setText("Take exam");
        btn_exam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_examActionPerformed(evt);
            }
        });
        add(btn_exam);
        btn_exam.setBounds(703, 402, 162, 40);

        btn_rating.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btn_rating.setText("Rating");
        btn_rating.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ratingActionPerformed(evt);
            }
        });
        add(btn_rating);
        btn_rating.setBounds(703, 492, 162, 40);

        btn_feedback.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btn_feedback.setText("Feedback");
        btn_feedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_feedbackActionPerformed(evt);
            }
        });
        add(btn_feedback);
        btn_feedback.setBounds(703, 582, 162, 40);

        btn_back.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btn_back.setText("<Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        add(btn_back);
        btn_back.setBounds(749, 721, 84, 34);

        jLabel2.setIcon(new javax.swing.ImageIcon("/Users/agash/Documents/The Boys/Student.png")); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(2, -3, 1500, 1000);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_syllabusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_syllabusActionPerformed
        // TODO add your handling code here:
        Stu_view_course_curriculum stu_view_course_curriculum = new Stu_view_course_curriculum(bottom_panel, students, professors, courses, student_details,coursePair);
        bottom_panel.add("stu_view_course_curriculum",stu_view_course_curriculum);
        CardLayout layout = (CardLayout) bottom_panel.getLayout();
        layout.next(bottom_panel); 
    }//GEN-LAST:event_btn_syllabusActionPerformed

    private void btn_announceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_announceActionPerformed
        // TODO add your handling code here:
        Stu_announcement stu_announcement = new Stu_announcement(bottom_panel, students, professors, courses, student_details,coursePair);
        bottom_panel.add("stu_announcement",stu_announcement);
        CardLayout layout = (CardLayout) bottom_panel.getLayout();
        layout.next(bottom_panel);         
    }//GEN-LAST:event_btn_announceActionPerformed

    private void btn_chatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chatActionPerformed
        // TODO add your handling code here:
        Stu_chatwithpeer stu_chatwithpeer = new Stu_chatwithpeer(bottom_panel, students, professors, courses, student_details,coursePair);
        bottom_panel.add("stu_chatwithpeer",stu_chatwithpeer);
        CardLayout layout = (CardLayout) bottom_panel.getLayout();
        layout.next(bottom_panel);         
    }//GEN-LAST:event_btn_chatActionPerformed

    private void btn_examActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_examActionPerformed
        // TODO add your handling code here:
        
        found = false;
        
        if (Course.isExam_set()==false){
            found =true;
            JOptionPane.showMessageDialog(null, "Exam is not yet set by the Professor");
        }
        
        
        for (ArrayList<String> studentGrades : grades) {
            String text = studentGrades.get(0);
            String grade = studentGrades.get(1);
            if (text.equals(Course.getTopic()) && grade.equals("Yet to take Exam")){
                JOptionPane.showMessageDialog(null, "You have already completed the exam!");
                found = true;
            }
        }
        
        if (found == false){
        Stu_take_exam stu_take_exam = new Stu_take_exam(bottom_panel, students, professors, courses, student_details,coursePair);
        bottom_panel.add("stu_take_exam",stu_take_exam);
        CardLayout layout = (CardLayout) bottom_panel.getLayout();
        layout.next(bottom_panel);
        }
    }//GEN-LAST:event_btn_examActionPerformed

    private void btn_ratingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ratingActionPerformed
        // TODO add your handling code here:
        Stu_rating stu_rating = new Stu_rating(bottom_panel, students, professors, courses, student_details,coursePair);
        bottom_panel.add("stu_rating",stu_rating);
        CardLayout layout = (CardLayout) bottom_panel.getLayout();
        layout.next(bottom_panel);         
    }//GEN-LAST:event_btn_ratingActionPerformed

    private void btn_feedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_feedbackActionPerformed
        // TODO add your handling code here:
        Stu_feedback stu_feedback = new Stu_feedback(bottom_panel, students, professors, courses, student_details,coursePair);
        bottom_panel.add("stu_feedback",stu_feedback);
        CardLayout layout = (CardLayout) bottom_panel.getLayout();
        layout.next(bottom_panel);          
    }//GEN-LAST:event_btn_feedbackActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        bottom_panel.remove(this);
        CardLayout layout = (CardLayout) bottom_panel.getLayout();
        layout.previous(bottom_panel);
    }//GEN-LAST:event_btn_backActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_announce;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_chat;
    private javax.swing.JButton btn_exam;
    private javax.swing.JButton btn_feedback;
    private javax.swing.JButton btn_rating;
    private javax.swing.JButton btn_syllabus;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
