/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;
import model.*;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import java.time.Duration;


import java.io.IOException;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.pdmodel.graphics.color.PDColor;
import org.apache.pdfbox.pdmodel.graphics.color.PDDeviceCMYK;
import org.apache.pdfbox.pdmodel.graphics.color.PDColor;
import org.apache.pdfbox.pdmodel.graphics.color.PDColorSpace;
import org.apache.pdfbox.pdmodel.graphics.color.PDDeviceRGB;

import java.awt.Color;



/**
 *
 * @author manish
 */
public class Stu_view extends javax.swing.JPanel {

    /**
     * Creates new form Stu_view
     */
    private Student_details_list students;
    private Professor_details_list professors;
    private Course_details_list  courses;
    private JPanel bottom_panel;
    private Student_details student_details;
    private ArrayList<ArrayList<String>> grades = new ArrayList();
    private Integer Counter = 0;
    private List<Double> gpa = new ArrayList<>(); 
    private String transcript;
    
    public Stu_view(JPanel bottom_panel, Student_details_list students, Professor_details_list professors, Course_details_list courses,Student_details student_details) {
        initComponents();
        this.bottom_panel = bottom_panel;
        this.students = students;
        this.professors = professors;
        this.courses = courses;
        this.student_details = student_details;
        this.grades = student_details.getGrades();
        
        for (ArrayList<String> item : grades) {
            if (item.get(3)=="Pass"){
                Counter+=1;
            }
        }
        if (Counter==8){
            student_details.setGraduated(true);
        }
        student_details.setGPA(gpa); 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_viewcourses = new javax.swing.JButton();
        btn_registercourse = new javax.swing.JButton();
        btn_progress = new javax.swing.JButton();
        btn_empmessage = new javax.swing.JButton();
        btn_scholarship = new javax.swing.JButton();
        btn_transcript = new javax.swing.JButton();
        btn_degree = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(null);

        btn_viewcourses.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btn_viewcourses.setText("View Registered Courses");
        btn_viewcourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_viewcoursesActionPerformed(evt);
            }
        });
        add(btn_viewcourses);
        btn_viewcourses.setBounds(643, 163, 240, 41);

        btn_registercourse.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btn_registercourse.setText("Register for a new Course");
        btn_registercourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registercourseActionPerformed(evt);
            }
        });
        add(btn_registercourse);
        btn_registercourse.setBounds(643, 87, 240, 41);

        btn_progress.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btn_progress.setText("Progress");
        btn_progress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_progressActionPerformed(evt);
            }
        });
        add(btn_progress);
        btn_progress.setBounds(643, 239, 240, 41);

        btn_empmessage.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btn_empmessage.setText("Employee Message");
        btn_empmessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_empmessageActionPerformed(evt);
            }
        });
        add(btn_empmessage);
        btn_empmessage.setBounds(643, 526, 240, 41);

        btn_scholarship.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btn_scholarship.setText("Scholarship");
        btn_scholarship.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_scholarshipActionPerformed(evt);
            }
        });
        add(btn_scholarship);
        btn_scholarship.setBounds(643, 315, 240, 41);

        btn_transcript.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btn_transcript.setText("Transcript");
        btn_transcript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_transcriptActionPerformed(evt);
            }
        });
        add(btn_transcript);
        btn_transcript.setBounds(643, 391, 240, 41);

        btn_degree.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btn_degree.setText("Degree");
        btn_degree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_degreeActionPerformed(evt);
            }
        });
        add(btn_degree);
        btn_degree.setBounds(643, 467, 240, 41);

        btn_back.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btn_back.setText("<Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        add(btn_back);
        btn_back.setBounds(721, 654, 82, 37);

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Student Portal");
        add(jLabel7);
        jLabel7.setBounds(6, 6, 1494, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon("/Users/agash/Documents/The Boys/Student.png")); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(2, -3, 1500, 1000);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_degreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_degreeActionPerformed
        // TODO add your handling code here:
        if(student_details.isGraduated()==true){
            System.setProperty("webdriver.chrome.driver", "/usr/local/bin/chromedriver");

            ChromeOptions chromeOptions = new ChromeOptions();
            chromeOptions.addArguments("--no-sandbox");
            chromeOptions.addArguments("--disable-dev-shm-usage");

            WebDriver driver = new ChromeDriver(chromeOptions);

            String formUrl = "https://docs.google.com/forms/d/e/1FAIpQLSecpWD3WhabFDdfyg4d9g70Z18y3vu5XsvU2f_UpDPwaogsTw/viewform?fbzx=-9022930997714453342";
            driver.get(formUrl);

            WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));

            String textInput1Xpath = "//*[@id='mG61Hd']/div[2]/div/div[2]/div[1]/div/div[1]/div[2]/div[1]/div/div[1]/input";
            WebElement textInput1 = wait.until(ExpectedConditions.elementToBeClickable(By.xpath(textInput1Xpath)));
            textInput1.sendKeys(student_details.getMailid());

            String textInput2Xpath = "//*[@id='mG61Hd']/div[2]/div/div[2]/div[2]/div/div/div[2]/div/div[1]/div/div[1]/input";
            WebElement textInput2 = wait.until(ExpectedConditions.elementToBeClickable(By.xpath(textInput2Xpath)));
            textInput2.sendKeys(student_details.getName());

            String submitButtonXpath = "//*[@id='mG61Hd']/div[2]/div/div[3]/div[1]/div[1]/div/span/span";
            WebElement submitButton = wait.until(ExpectedConditions.elementToBeClickable(By.xpath(submitButtonXpath)));
            submitButton.click();

            driver.quit();
            JOptionPane.showMessageDialog(null, "Your degree certificate will be sent to your registered mail ID shortly!");
        }
        else {
            JOptionPane.showMessageDialog(null, "You are not yet eligible to receive your degree certificate");
        }
    }//GEN-LAST:event_btn_degreeActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        bottom_panel.remove(this);
        CardLayout layout = (CardLayout) bottom_panel.getLayout();
        layout.previous(bottom_panel);         
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_registercourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registercourseActionPerformed
        // TODO add your handling code here:
        Stu_register_newcourse stu_register_newcourse = new Stu_register_newcourse(bottom_panel, students, professors, courses, student_details);
        bottom_panel.add("stu_register_newcourse",stu_register_newcourse);
        CardLayout layout = (CardLayout) bottom_panel.getLayout();
        layout.next(bottom_panel);  
    }//GEN-LAST:event_btn_registercourseActionPerformed

    private void btn_viewcoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_viewcoursesActionPerformed
        // TODO add your handling code here:
        Stu_view_registered_courses stu_view_registered_courses = new Stu_view_registered_courses(bottom_panel, students, professors, courses, student_details);
        bottom_panel.add("stu_view_registered_courses",stu_view_registered_courses);
        CardLayout layout = (CardLayout) bottom_panel.getLayout();
        layout.next(bottom_panel); 
    }//GEN-LAST:event_btn_viewcoursesActionPerformed

    private void btn_transcriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_transcriptActionPerformed
        // TODO add your handling code here:
//        Stu_transcript stu_transcript = new Stu_transcript(bottom_panel, students, professors, courses, student_details);
//        bottom_panel.add("stu_transcript",stu_transcript);
//        CardLayout layout = (CardLayout) bottom_panel.getLayout();
//        layout.next(bottom_panel); 
    

    try {
            PDDocument document = new PDDocument();
            PDPage page = new PDPage(PDRectangle.A4);
            document.addPage(page);

            PDPageContentStream contentStream = new PDPageContentStream(document, page);

 
            PDType1Font titleFont = PDType1Font.HELVETICA_BOLD;
            contentStream.setFont(titleFont, 16);

            contentStream.beginText();
            contentStream.newLineAtOffset(100, 750); 
            contentStream.showText("Athena Edu.");
            contentStream.endText();


            PDType1Font nameFont = PDType1Font.HELVETICA;
            contentStream.setFont(nameFont, 14);


            contentStream.beginText();
            contentStream.newLineAtOffset(100, 730); 
            contentStream.showText("Name: " + student_details.getName());
            contentStream.endText();


            PDType1Font headerFont = PDType1Font.HELVETICA_BOLD;
            contentStream.setFont(headerFont, 12);


            contentStream.beginText();
            contentStream.newLineAtOffset(100, 710); 
            contentStream.showText("Subject");
            contentStream.newLineAtOffset(150, 0); 
            contentStream.showText("Term");
            contentStream.newLineAtOffset(100, 0); 
            contentStream.showText("Grade");
            contentStream.endText();

            PDType1Font dataFont = PDType1Font.HELVETICA;
            contentStream.setFont(dataFont, 12);


            float yPosition = 690; 

            for (ArrayList<String> innerList : grades) {
                yPosition -= 20; 
                contentStream.beginText();
                contentStream.newLineAtOffset(100, yPosition); 
                contentStream.showText(innerList.get(0));
                contentStream.newLineAtOffset(150, 0); 
                contentStream.showText(innerList.get(1));
                contentStream.newLineAtOffset(100, 0); 
                contentStream.showText(innerList.get(2));
                contentStream.endText();
            }

            contentStream.close();

            document.save("Transcript.pdf");
            document.close();
            JOptionPane.showMessageDialog(null, "Transcript generated and saved as PDF");
        }
    
    catch (IOException e) {
            JOptionPane.showMessageDialog(null, "An unexpected error occured.");
        }
    }//GEN-LAST:event_btn_transcriptActionPerformed

    private void btn_scholarshipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_scholarshipActionPerformed
        // TODO add your handling code here:
        Stu_scholarship stu_scholarship = new Stu_scholarship(bottom_panel, students, professors, courses, student_details);
        bottom_panel.add("stu_scholarship",stu_scholarship);
        CardLayout layout = (CardLayout) bottom_panel.getLayout();
        layout.next(bottom_panel);         
    }//GEN-LAST:event_btn_scholarshipActionPerformed

    private void btn_progressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_progressActionPerformed
        // TODO add your handling code here:
        Stu_progress stu_progress = new Stu_progress(bottom_panel, students, professors, courses, student_details);
        bottom_panel.add("stu_progress",stu_progress);
        CardLayout layout = (CardLayout) bottom_panel.getLayout();
        layout.next(bottom_panel);         
    }//GEN-LAST:event_btn_progressActionPerformed

    private void btn_empmessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_empmessageActionPerformed
        // TODO add your handling code here:
        if (!student_details.getChats().trim().isEmpty()){
            Stu_emp_msg stu_emp_msg = new Stu_emp_msg(bottom_panel, student_details);
            bottom_panel.add("stu_emp_msg",stu_emp_msg);
            CardLayout layout = (CardLayout) bottom_panel.getLayout();
            layout.next(bottom_panel);            
        }
        else {
            JOptionPane.showMessageDialog(null, "Employee messaging feature is disabled");
        }
    }//GEN-LAST:event_btn_empmessageActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_degree;
    private javax.swing.JButton btn_empmessage;
    private javax.swing.JButton btn_progress;
    private javax.swing.JButton btn_registercourse;
    private javax.swing.JButton btn_scholarship;
    private javax.swing.JButton btn_transcript;
    private javax.swing.JButton btn_viewcourses;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
